{
	% CSC488 declaration function test-Failing case
	
	func test(x:integer):integer{
	    result 3
	}
	func test(x:integer):integer{
	    result 4
	}
	put 5
}
